package test.java;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import main.java.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'AndreaZ' at '27/10/16 11:01 PM' with Gradle 3.1
 *
 * @author AndreaZ, @date 27/10/16 11:01 PM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
